const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const PORT=process.env.PORT||3000, ROOT=__dirname, PUB=path.join(ROOT,'public'), DATA_DIR=process.env.DATA_DIR||ROOT, DBFILE=path.join(DATA_DIR,'data.json'), SESSION_TTL=Number(process.env.SESSION_TTL_MS||86400000);
if(!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR,{recursive:true});
const sessions=new Map(),clients=new Set();
function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,h){const [s,d]=h.split(':');return !!s&&!!d&&crypto.timingSafeEqual(Buffer.from(d,'hex'),crypto.scryptSync(p,s,64))}
function initial(){return {users:[{id:1,username:'admin',role:'admin',name:'Administrator',passwordHash:hash('admin123')},{id:2,username:'storekeeper',role:'storekeeper',name:'Storekeeper',passwordHash:hash('store123')}],items:[{id:1,number:1,name:'Rice',cat:'Food',unit:'kg',qty:35,min:15},{id:2,number:2,name:'Beans',cat:'Food',unit:'kg',qty:20,min:8},{id:3,number:3,name:'Palm Oil',cat:'Food',unit:'L',qty:4,min:5},{id:4,number:1,name:'Guinness',cat:'Drinks',unit:'crates',qty:8,min:4},{id:5,number:2,name:'Coca-Cola',cat:'Drinks',unit:'bottles',qty:8,min:10}],issues:[],movements:[],supplies:[],dailyOpenings:{}}}
let db=fs.existsSync(DBFILE)?JSON.parse(fs.readFileSync(DBFILE,'utf8')):initial();
function migrate(){db.issues=db.issues||[];db.movements=db.movements||[];db.supplies=db.supplies||[];db.dailyOpenings=db.dailyOpenings||{};db.items=db.items||[];for(const i of db.items){i.cat=i.cat==='Bar'?'Drinks':(i.cat||'Food');if(i.number==null)i.number=nextNumber(i.cat,i.id);if(i.qty==null)i.qty=0;if(i.min==null)i.min=0}save()}
function save(){fs.writeFileSync(DBFILE,JSON.stringify(db,null,2))}
function nextNumber(cat,ignoreId){let nums=db.items.filter(i=>i.cat===cat&&i.id!==ignoreId).map(i=>Number(i.number)).filter(Number.isFinite);return nums.length?Math.max(...nums)+1:1}
function today(){return new Date().toISOString().slice(0,10)}
function ensureOpening(date=today()){if(!db.dailyOpenings[date])db.dailyOpenings[date]={};for(const i of db.items)if(db.dailyOpenings[date][i.id]==null)db.dailyOpenings[date][i.id]=i.qty;}
function send(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(b)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const t=h.slice(7),s=sessions.get(t);if(!s)return null;if(s.expiresAt<Date.now()){sessions.delete(t);return null}return s}
function broadcast(type,data){const msg=`data: ${JSON.stringify({type,...data})}\n\n`;for(const r of clients){try{r.write(msg)}catch{clients.delete(r)}}}
function low(){return db.items.filter(i=>i.qty<=i.min)}
function movement(item,type,qty,by,extra={}){db.movements.push({id:Date.now()+Math.random(),date:today(),itemId:item.id,itemNumber:item.number,item:item.name,category:item.cat,type,qty,by,...extra})}
function state(){ensureOpening();const d=today(),issuesToday=db.issues.filter(x=>x.date===d),confirmedToday=db.supplies.filter(x=>x.date===d&&x.confirmed);const items=db.items.map(i=>{const opening=db.dailyOpenings[d]?.[i.id]??i.qty,newStock=confirmedToday.filter(s=>s.itemId===i.id).reduce((a,s)=>a+s.received,0),issuedToday=issuesToday.filter(x=>x.itemId===i.id).reduce((a,x)=>a+x.qty,0);return {...i,openingStock:opening,newStock,totalStock:opening+newStock,issuedToday,balance:i.qty}});return {items,issues:db.issues,supplies:db.supplies,movements:db.movements,low:low()}}
async function route(req,res){
 const u=url.parse(req.url,true),p=u.pathname;
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS'});return res.end()}
 if(p==='/api/login'&&req.method==='POST'){const x=await body(req),user=db.users.find(z=>z.username===x.username);if(!user||!verify(x.password||'',user.passwordHash))return send(res,401,{error:'Invalid login'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{id:user.id,username:user.username,role:user.role,name:user.name,expiresAt:Date.now()+SESSION_TTL});return send(res,200,{token,user:{id:user.id,username:user.username,role:user.role,name:user.name}})}
 if(p==='/api/events'){const me=auth(req);if(!me)return send(res,401,{error:'Unauthorized'});res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','Access-Control-Allow-Origin':'*'});res.write(`data: ${JSON.stringify({type:'connected'})}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return}
 if(p==='/api/health'&&req.method==='GET')return send(res,200,{ok:true,service:'uyan-inventory',time:new Date().toISOString()});
 const me=auth(req);if(!me)return send(res,401,{error:'Unauthorized'});
 if(p==='/api/state'&&req.method==='GET')return send(res,200,state());
 if(p==='/api/items'&&req.method==='POST'){if(!['storekeeper','admin'].includes(me.role))return send(res,403,{error:'Forbidden'});const x=await body(req),cat=x.cat==='Drinks'?'Drinks':'Food';if(!x.name||!x.unit)return send(res,400,{error:'Name and unit required'});const i={id:Date.now(),number:nextNumber(cat),name:String(x.name).trim(),cat,unit:String(x.unit).trim(),qty:Number(x.qty)||0,min:Number(x.min)||0};ensureOpening();db.items.push(i);db.dailyOpenings[today()][i.id]=i.qty;movement(i,'Opening Stock',i.qty,me.username);save();broadcast('state',{message:'Inventory item added'});return send(res,201,i)}
 if(p.startsWith('/api/items/')&&req.method==='POST'&&p.endsWith('/adjust')){if(!['storekeeper','admin'].includes(me.role))return send(res,403,{error:'Forbidden'});const id=Number(p.split('/')[3]),i=db.items.find(x=>x.id===id);if(!i)return send(res,404,{error:'Item not found'});const x=await body(req),a=Number(x.adjustment)||0;if(!a)return send(res,400,{error:'No adjustment'});i.qty+=a;movement(i,'Adjustment',a,me.username,{reason:x.reason||''});save();broadcast('stock',{item:i.name,qty:i.qty,low:i.qty<=i.min});return send(res,200,i)}
 if(p==='/api/supplies'&&req.method==='POST'){if(!['storekeeper','admin'].includes(me.role))return send(res,403,{error:'Forbidden'});const x=await body(req),i=db.items.find(z=>z.id===Number(x.itemId)),q=Number(x.received)||0;if(!i||q<=0)return send(res,400,{error:'Invalid item or quantity'});const s={id:Date.now(),date:today(),itemId:i.id,itemNumber:i.number,item:i.name,category:i.cat,supplier:String(x.supplier||'').trim(),expected:Number(x.expected)||q,received:q,unit:i.unit,amount:Number(x.amount)||0,receiptNo:String(x.receiptNo||''),notes:String(x.notes||''),recordedBy:me.username,confirmed:false,confirmedBy:null,confirmedAt:null};db.supplies.push(s);save();broadcast('supply',{supply:s});return send(res,201,s)}
 if(p.startsWith('/api/supplies/')&&p.endsWith('/confirm')&&req.method==='POST'){if(!['admin','storekeeper'].includes(me.role))return send(res,403,{error:'Forbidden'});const id=Number(p.split('/')[3]),s=db.supplies.find(x=>x.id===id);if(!s)return send(res,404,{error:'Supply not found'});if(s.confirmed)return send(res,200,s);const i=db.items.find(x=>x.id===s.itemId);if(!i)return send(res,404,{error:'Item not found'});i.qty+=s.received;s.confirmed=true;s.confirmedBy=me.username;s.confirmedAt=new Date().toISOString();movement(i,'Confirmed Supply',s.received,me.username,{supplier:s.supplier,supplyId:s.id,amount:s.amount});save();broadcast('supply_confirmed',{supply:s});return send(res,200,s)}
 if(p==='/api/issues'&&req.method==='POST'){if(!['storekeeper','admin'].includes(me.role))return send(res,403,{error:'Forbidden'});const x=await body(req),i=db.items.find(z=>z.id===Number(x.itemId)),q=Number(x.qty);if(!i||!q||q>i.qty)return send(res,400,{error:'Invalid item or quantity'});const dept=x.department==='Bar'?'Bar':'Kitchen';if((dept==='Kitchen'&&i.cat!=='Food')||(dept==='Bar'&&i.cat!=='Drinks'))return send(res,400,{error:'Food and Drinks issues must stay separate'});const issue={id:Date.now(),date:today(),itemId:i.id,itemNumber:i.number,item:i.name,category:i.cat,unit:i.unit,qty:q,department:dept,receiver:String(x.receiver||'').trim(),by:me.username,confirmed:false,confirmedAt:null,confirmedBy:null};db.issues.push(issue);i.qty-=q;movement(i,'Issued to '+dept,-q,me.username,{receiver:issue.receiver,issueId:issue.id});save();broadcast('issue',{issue,low:i.qty<=i.min});return send(res,201,issue)}
 if(p.startsWith('/api/issues/')&&p.endsWith('/confirm')&&req.method==='POST'){if(!['admin','storekeeper'].includes(me.role))return send(res,403,{error:'Forbidden'});const id=Number(p.split('/')[3]),i=db.issues.find(x=>x.id===id);if(!i)return send(res,404,{error:'Issue not found'});i.confirmed=true;i.confirmedAt=new Date().toISOString();i.confirmedBy=me.username;save();broadcast('issue_confirmed',{id});return send(res,200,i)}
 if(p==='/api/reports/weekly'&&req.method==='GET'){ensureOpening();const end=new Date(),start=new Date();start.setDate(end.getDate()-6);const from=start.toISOString().slice(0,10),to=end.toISOString().slice(0,10),arr=db.movements.filter(x=>x.date>=from&&x.date<=to);return send(res,200,{from,to,movements:arr,issues:db.issues.filter(x=>x.date>=from&&x.date<=to),supplies:db.supplies.filter(x=>x.date>=from&&x.date<=to),low:low()})}
 if(p==='/api/reset'&&req.method==='POST'){if(me.role!=='admin')return send(res,403,{error:'Forbidden'});db=initial();save();broadcast('reset',{});return send(res,200,{ok:true})}
if(p==='/'&&req.method==='GET'){
  const html=fs.readFileSync(path.join(ROOT,'prototype.html'),'utf8');
  res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});
  return res.end(html);
} return send(res,404,{error:'Not found'});
}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))route(req,res).catch(e=>send(res,500,{error:e.message}));else{let file=pSafe(req.url==='/'?'/index.html':req.url);if(!file)return send(res,404,{error:'Not found'});const ext=path.extname(file),ct={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct});fs.createReadStream(file).pipe(res)}});
function pSafe(u){const q=decodeURIComponent(u.split('?')[0]);const f=path.normalize(path.join(PUB,q));return f.startsWith(PUB+path.sep)&&fs.existsSync(f)?f:null}
migrate();server.listen(PORT,()=>console.log(`UYAN Inventory running on http://localhost:${PORT}`));
